---
`title: "Water Conservation Shiny App"
author: "Claudia Flores"
date: "2/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
# Load in packages. 
library(tidyverse)
library(tidyr) 
library(janitor)
library(prodlim)
library(dplyr)
library(stringr)
library(sf)
library(here)
library(lubridate)
library(anytime)
library(zoo)
```

To do:
1.) Clean data
2.) Merge data together and add GIS data
3.) Set up UI and Server for app, create app.R file, Select theme and type
4.) Start working on widgets 

```{r}
# Load in data and format column names.
water_conservation <- read_csv("uw_supplier_data010720.csv") %>% 
  clean_names()
water_supplier <- read_csv("Water_Districts.csv") %>% 
  clean_names()

# Select agencyname, global_id from water_supplier dataframe.
water_supplier_clean <- water_supplier %>% 
  select(agencyname,global_id)

# Rename agencyname column in water_supplier dataframe to supplier_name.
water_supplier_clean <- water_supplier_clean %>%
  dplyr::rename(supplier_name = agencyname)

# Remove white spaces in and from both sides of text for supplier_name column in both datafames.
water_supplier_clean <- water_supplier_clean %>% 
  mutate(supplier_name = stringr::str_squish(supplier_name)) %>% 
  mutate(supplier_name = stringr::str_to_title(supplier_name))

water_conservation <- water_conservation %>% 
  mutate(supplier_name = stringr::str_squish(supplier_name)) %>% 
  mutate(supplier_name = stringr::str_to_title(supplier_name))

# Merge datasets.
water_merged <- merge(water_conservation,water_supplier_clean, by = "supplier_name")

# Change reporting_month column to date format.
water_merged <- water_merged %>% 
   mutate(yy_mm_dd = lubridate::parse_date_time(reporting_month, "my"))
         
# Check number of unique observations in water_conservation dataframe supplier_name column.
water_conservation_dup <- water_conservation %>% 
  distinct(supplier_name) 

# See what observations cannot be matched in water_merged from water_conservation and water_supplier dataframes.
missing_data <- anti_join(water_supplier_clean, water_conservation, by = "supplier_name")

# Water supplier data with proper shapefiles
water_supplier_spatial <- read_sf(dsn = here("spatial_data"), layer = "Water_Districts") %>%
  clean_names() %>% 
  select(agencyname) %>% 
  dplyr::rename(supplier_name = agencyname) %>% 
  mutate(supplier_name = stringr::str_squish(supplier_name)) %>% 
  mutate(supplier_name = stringr::str_to_title(supplier_name))

# Water supplier spatial data with water conservation
water_total <-  merge(water_conservation,water_supplier_spatial, by = "supplier_name") %>% 
  st_as_sf() 

# Read in ca_counties spatial data

ca_counties <- read_sf(dsn = here("CA_Counties"), layer = "CA_Counties_TIGER2016") %>%
  st_transform(crs = 4326) %>% 
  select(NAME)


```


















